"""Extraction checked against genuinely real, publicly-published sample
invoices — not anything generated by this repo's own code, and not any
real transaction (both are demo/template documents by design, published by
their source specifically to be used as examples). Sources:

- canadapost.pdf: https://www.canadapost-postescanada.ca/cpc/doc/en/postal-services/sample-pdf-invoice.pdf
- slicedinvoices.pdf: https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf
"""
from datetime import date
from pathlib import Path

from ledger_reconciler.extract import extract_invoice

SAMPLES = Path(__file__).parent / "_public_samples"


def test_slicedinvoices_extracts_cleanly():
    inv = extract_invoice(SAMPLES / "slicedinvoices.pdf")
    assert inv.invoice_number == "INV-3337"
    assert inv.vendor == "DEMO - Sliced Invoices"
    assert inv.invoice_date == date(2016, 1, 25)
    assert inv.amount == 93.50


def test_canadapost_multicolumn_layout_degrades_honestly():
    """This one's a genuinely hard case: real multi-column layout where
    text-layer extraction scrambles the reading order, so a label and its
    value end up far apart in the raw text. The amount still comes through
    (it has a clean, unambiguous label nearby); the rest correctly comes
    back None rather than grabbing a wrong value from a neighboring column
    — that's the behavior that matters here, not perfect extraction."""
    inv = extract_invoice(SAMPLES / "canadapost.pdf")
    assert inv.amount == 1673.01
    assert inv.invoice_number is None
    assert inv.vendor is None
    assert inv.invoice_date is None
