import { expect, test } from 'vitest'
import { sequenceRatio } from '../src/domain/similarity'

/**
 * Expected values were generated by running Python's
 * `difflib.SequenceMatcher(None, a, b).ratio()` on these exact pairs, not
 * derived by hand. If this port drifts from CPython's algorithm these fail
 * immediately, which is the whole point: the reconciliation logic depends
 * on this ratio meeting a 0.5 threshold, so a different similarity metric
 * would silently change which vendors match.
 */
const PY_REFERENCE: Array<[string, string, number]> = [
  ['acme co', 'payment to acme co', 0.56],
  ['Bluefern Supplies Ltd', 'Payment to Bluefern Supplies Ltd', 0.7924528301886793],
  ['nordway logistics', 'wire transfer - amberlake facilities', 0.33962264150943394],
  ['', '', 1.0],
  ['abc', '', 0.0],
  ['abcdef', 'abcdef', 1.0],
  ['kitten', 'sitting', 0.6153846153846154],
  ['cedar & finch consulting', 'consulting retainer - march', 0.39215686274509803],
  ['a', 'b', 0.0],
  ['aaaa', 'aa', 0.6666666666666666],
  ['meridian print services', 'payment to meridian print services', 0.8070175438596491],
]

test.each(PY_REFERENCE)(
  'matches CPython difflib for (%j, %j)',
  (a, b, expected) => {
    expect(sequenceRatio(a, b)).toBeCloseTo(expected, 12)
  },
)

/**
 * Exercises the autojunk path, which only engages at 200+ elements. Value
 * generated from CPython on this exact pair.
 *
 * Worth knowing: with isjunk=None, autojunk almost never changes the final
 * ratio, because purging popular characters from the index does not lose
 * the match. find_longest_match's extension pass re-matches them by direct
 * comparison. So this branch is fidelity insurance rather than something
 * that alters results, and the test's job is to prove the port still
 * agrees with CPython once the branch is live.
 */
test('agrees with CPython at lengths where autojunk engages', () => {
  const a = 'acme corporation limited'
  const b = 'payment to acme corporation limited ' + 'x'.repeat(180)
  expect(b.length).toBeGreaterThanOrEqual(200)
  expect(sequenceRatio(a, b)).toBeCloseTo(0.2, 12)
})

/**
 * ratio() is NOT symmetric, and the port reproduces that. The algorithm
 * indexes the second argument and scans the first against it, so swapping
 * them can change the result. Verified against CPython, which returns
 * exactly these two values for this pair.
 *
 * This is pinned deliberately: `match.ts` calls sequenceRatio(vendor,
 * description) in that order, and quietly swapping the arguments would
 * change which vendors match without any test failing elsewhere.
 */
test('reproduces CPython asymmetry, argument order is load-bearing', () => {
  const a = 'nordway logistics'
  const b = 'wire transfer - amberlake facilities'
  expect(sequenceRatio(a, b)).toBeCloseTo(0.33962264150943394, 12)
  expect(sequenceRatio(b, a)).toBeCloseTo(0.22641509433962265, 12)
})
